import Link from 'next/link'
import { ArrowRight, Check, CircleDot, Layers3, Sparkles } from 'lucide-react'
import { AccentIcon, Shell } from '@/components/design-system'
import { screens } from '@/components/screen-data'

export default function Page() {
  return <Shell><main className="mx-auto max-w-7xl px-4 pb-16 sm:px-6 lg:pb-24">
    <section className="grid gap-12 border-b border-border py-16 lg:grid-cols-[1fr_0.72fr] lg:items-end lg:py-24">
      <div><div className="mb-8 flex items-center gap-3 font-mono text-[11px] uppercase tracking-[0.2em] text-primary"><CircleDot className="size-3" /> archive sequence / 2026</div><h1 className="max-w-4xl text-5xl font-semibold leading-[0.96] tracking-[-0.06em] text-balance sm:text-7xl lg:text-8xl">Five references.<br /><span className="text-muted-foreground">One clear system.</span></h1><p className="mt-8 max-w-xl text-base leading-7 text-muted-foreground">A fully ordered design archive assembled from AI Builder, dashboard, UI blocks, UI kit, and OpenPage references. Explore the complete flow or enter any screen directly.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/designs/ai-builder" className="inline-flex items-center gap-2 rounded-lg bg-primary px-5 py-3 text-sm font-medium text-primary-foreground transition-transform hover:-translate-y-0.5">Start the sequence <ArrowRight className="size-4" /></Link><a href="#screens" className="inline-flex items-center gap-2 rounded-lg border border-border px-5 py-3 text-sm font-medium hover:bg-accent">View all screens</a></div></div>
      <div className="relative rounded-2xl border border-border bg-card p-6 sm:p-8"><div className="absolute right-6 top-6 size-2 rounded-full bg-primary shadow-[0_0_18px_var(--primary)]" /><div className="mb-12 flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Layers3 className="size-5" /></span><div><p className="font-mono text-xs font-semibold">SYSTEM MAP</p><p className="text-xs text-muted-foreground">All modules connected</p></div></div><div className="space-y-5">{screens.map((screen, index) => <div key={screen.slug} className="flex items-center gap-4"><span className="font-mono text-[10px] text-muted-foreground/60">0{index + 1}</span><div className="h-px flex-1 bg-border" /><span className="font-mono text-xs text-muted-foreground">{screen.label}</span><Check className="size-3 text-primary" /></div>)}</div></div>
    </section>
    <section id="screens" className="py-16 lg:py-20"><div className="mb-8 flex items-end justify-between"><div><p className="font-mono text-[11px] uppercase tracking-[0.2em] text-muted-foreground">The complete flow</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em]">Every screen, in order.</h2></div><span className="hidden font-mono text-xs text-muted-foreground sm:block">{screens.length} modules / linked</span></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{screens.map((screen, index) => <Link key={screen.slug} href={`/designs/${screen.slug}`} className={`group rounded-2xl border border-border bg-card p-6 transition-all hover:-translate-y-1 hover:border-primary/50 ${index === 0 ? 'lg:col-span-2 lg:p-8' : ''}`}><div className="flex items-start justify-between"><AccentIcon type={screen.accent} /><span className="font-mono text-[10px] text-muted-foreground">{screen.eyebrow}</span></div><h3 className="mt-12 text-2xl font-semibold tracking-[-0.04em]">{screen.label}</h3><p className="mt-3 max-w-sm text-sm leading-6 text-muted-foreground">{screen.description}</p><div className="mt-8 flex items-center gap-2 font-mono text-[11px] uppercase tracking-wider text-primary">Open screen <ArrowRight className="size-3 transition-transform group-hover:translate-x-1" /></div></Link>)}</div></section>
    <footer className="flex flex-col gap-3 border-t border-border pt-6 font-mono text-[10px] uppercase tracking-wider text-muted-foreground sm:flex-row sm:justify-between"><span>Built as one connected reference system</span><span>AI Builder × shadcn × OpenPage</span></footer>
  </main></Shell>
}
